import {
  banner1,
  banner2,
  banner3,
  banner4,
  banner5,
  banner6,
  banner7,
  banner8,
  banner9,
  banner10,
} from "../public/assets/homeSliders";
import {
  mobileBanner1,
  mobileBanner2,
  mobileBanner3,
  mobileBanner4,
  mobileBanner5,
  mobileBanner6,
  mobileBanner7,
  mobileBanner8,
  mobileBanner9,
  mobileBanner10,
} from "../public/assets/homeSliders/mobile";
import {
  logoType1,
  logoType2,
  logoType3,
  logoType4,
  logoType5,
  logoType6,
  logoType7,
  logoType8,
  logoType9,
  logoType10,
} from "../public/assets/homeSliders/miniBanners";
export const HomeslidersDate = [
  {
    persianTitle: "سگ های نگهبان : فیلم بزرگ",
    englishTitle: "PAW Patrol: The Mighty Movie",
    banner: banner1,
    mobileBanner: mobileBanner1,
    descr: `شهاب سنگی جادویی در «شهر ماجراجویی» سقوط می کند
    و باعث می شود سگ های نگهبان دارای نیروهای ابرقهرمانی شوند
   و به «سگ های بزرگ» تبدیل شوند.`,
    id: 1,
    miniBanner: logoType1,
    tmdbId: 893723,
  },
  {
    persianTitle: "آی بی 71",
    englishTitle: "IB 71",
    banner: banner2,
    mobileBanner: mobileBanner2,
    descr: `افسران اطلاعاتی هندوستان قدم به ماموریت پرخطری می‌گذارند تا توطئه دشمن کشور خود را خنثی کنند…`,
    id: 2,
    miniBanner: logoType2,
    tmdbId: 1114114,
  },
  {
    persianTitle: "گرن توریسمو",
    englishTitle: "Gran Turismo",
    banner: banner3,
    mobileBanner: mobileBanner3,
    descr: `چطور میشه یک راننده واقعی اتومبیل‌های مسابقه‌ای حرفه‌ای شد؟!`,
    id: 3,
    miniBanner: logoType3,
    tmdbId: 980489,
  },
  {
    persianTitle: " جعبه پرنده بارسلونا",
    englishTitle: "Bird Box: Barcelona",
    banner: banner4,
    mobileBanner: mobileBanner4,
    descr: `تلاش برای بقا در خیابان‌های متروک بارسلون`,
    id: 4,
    miniBanner: logoType4,
    tmdbId: 805320,
  },
  {
    persianTitle: " استخراج ۲",
    englishTitle: "Extraction 2",
    banner: banner5,
    mobileBanner: mobileBanner5,
    descr: `اکشن چشم‌نواز`,
    id: 5,
    miniBanner: logoType5,
    tmdbId: 697843,
  },
  {
    persianTitle: "نگهبانان کهکشان ۳",
    englishTitle: "Guardians of the Galaxy Vol. 3 done",
    banner: banner6,
    mobileBanner: mobileBanner6,
    descr: `نگهبانان کهکشان ماموریتی دارند که در صورت عدم موفقیت می‌تواند به معنای پایان کار آن‌ها باشد…`,
    id: 6,
    miniBanner: logoType6,
    tmdbId: 447365,
  },
  {
    persianTitle: "تبدیل شوندگان: ظهور هیولاها",
    englishTitle: "Transformers: Rise of the Beasts",
    banner: banner7,
    mobileBanner: mobileBanner7,
    descr: `با هم متحد شوید یا سقوط کنید…`,
    id: 7,
    miniBanner: logoType7,
    tmdbId: 667538,
  },
  {
    persianTitle: "سریع و خشن ۱۰",
    englishTitle: "Fast X",
    mobileBanner: mobileBanner8,
    banner: banner8,
    descr: `سمفونی سرعت و تخیل`,
    id: 8,
    miniBanner: logoType8,
    tmdbId: 385687,
  },
  {
    persianTitle: "مگ ۲: خندق اقیانوسی",
    englishTitle: "Meg 2: The Trench",
    banner: banner9,
    mobileBanner: mobileBanner9,
    descr: `هیجانی میخکوب کننده`,
    id: 9,
    miniBanner: logoType9,
    tmdbId: 615656,
  },
  {
    persianTitle: "آسوکا",
    englishTitle: "Ahsoka",
    banner: banner10,
    mobileBanner: mobileBanner10,
    descr: `پس از سقوط امپراتوری کهکشان، آسوکا تانو
    شوالیه سابق جدای، درباره تهدید تازه‌ای تحقیق می‌کند…`,
    id: 10,
    miniBanner: logoType10,
    tmdbId: 1166427,
  },
];
